version: '3'

services:
    borderlands:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: borderlands
        restart: always
        command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/usr/src
        ports:
            - 8200:8000
